name: Python lints, formats and test

on:
  push:
    paths: ['**.py', '**.pyi']
    branches:
      - main
  pull_request:
    paths: ['**.py', '**.pyi']
    
jobs:
  python-format:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv, basedpyright, ruff
        run: pip install uv basedpyright ruff

      - name: Intialize project dependencies
        run: uv sync

      - name: Check format
        run: ruff check --diff --respect-gitignore .

      - name: Type checking
        run: basedpyright .
